#! /usr/bin/env python
import sys
import itertools

for markdown, lines in itertools.groupby(open(sys.argv[1]).readlines(), key=lambda line: line.startswith('#')):
    if markdown:
        print(''.join(line.lstrip('# ') for line in lines))
    else:
        print('\n```python')
        print(''.join(lines).strip())
        print('```\n')
