#! /usr/bin/env python
import sys
import itertools

for k, g in itertools.groupby(open(sys.argv[1]).readlines(), key=lambda line: line.startswith('#')):
    if k:
        print(''.join(line[2:] for line in g))
    else:
        print('\n```python')
        print(''.join(g))
        print('```\n')
