#! /usr/bin/env python
import sys

blocks = ('\n' + open(sys.argv[1]).read()).split("\n'''\n")
assert len(blocks) % 2 == 1

code = True
for block in blocks:
    if code and block.strip():
        print('\n```python')
        print(block.strip())
        print('```\n')
    elif not code:
        print(block.strip())
    code = not code
